# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HoursSigner < Formula
  desc "A tool to add signature blocks to hours/timesheet PDFs"
  homepage "https://github.com/joelgrimberg/hours-signer"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joelgrimberg/hours-signer/releases/download/v1.0.2/hours-signer_1.0.2_darwin_amd64.tar.gz"
      sha256 "b845b3c71a6c51e8fb3a3ba7f7a36bc305de01bce064a8bc3ccde732e8ee6470"

      def install
        bin.install "hours-signer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joelgrimberg/hours-signer/releases/download/v1.0.2/hours-signer_1.0.2_darwin_arm64.tar.gz"
      sha256 "122e079747a2dc7887e602306809f4e5d2e1ea6cd300344d5ad7341f0c285dc0"

      def install
        bin.install "hours-signer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joelgrimberg/hours-signer/releases/download/v1.0.2/hours-signer_1.0.2_linux_amd64.tar.gz"
      sha256 "7ea4c8c3be9facd177af4e0d30acfcb0c0c493ff326011d209330029ecfa2b55"
      def install
        bin.install "hours-signer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joelgrimberg/hours-signer/releases/download/v1.0.2/hours-signer_1.0.2_linux_arm64.tar.gz"
      sha256 "cdcbb09f66188ed60a56926d8cb94168c691a404055249b95eb83e9d63f42283"
      def install
        bin.install "hours-signer"
      end
    end
  end

  test do
    system "#{bin}/hours-signer", "-show-config"
  end
end
